version: '3'
services:

  backend: 
    image: saraaguilo/proyectoea:0.1.1
    restart: always
    ports:
      - "9090:9090"


  backoffice:
    image: saraaguilo/backoffice:0.1.2

    restart: always
    depends_on:
      - proyectoea
    ports:
      - "8080:80"