version: '3'
services:

  backend: 
    image: saraaguilo/proyecto_ea31:0.0.2
    restart: always
    ports:
      - "9090:9090"


  backoffice:
    image: saraaguilo/backoffice1:0.0.1

    restart: always
    depends_on:
      - backend
    ports:
      - "8181:80"

  frontend:
    image: saraaguilo/flutter1:0.0.2

    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"

  mongo:
    image: mongo:latest

    restart: always
    depends_on:
      - backend
    ports:
      - "27017:27017"